FROM maven:3.8.6-openjdk-8 AS builder

WORKDIR /app

COPY java-node/ .
#COPY java-node/src ./src
#COPY protos/raft.proto ./src/main/proto

# Build the application
RUN mvn clean package assembly:single

# Create runtime image
FROM openjdk:8-jre-alpine

WORKDIR /app

# Copy the built application (with dependencies)
COPY --from=builder /app/target/java-raft-1.0-SNAPSHOT-jar-with-dependencies.jar app.jar

# Run the server
CMD ["java", "-jar", "app.jar"]