// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package grpc;

public interface AppendEntriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AppendEntriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 term = 1;</code>
   */
  int getTerm();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();
}
