// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package grpc;

public interface LogEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LogEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 term = 1;</code>
   */
  int getTerm();

  /**
   * <code>string command = 2;</code>
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 2;</code>
   */
  com.google.protobuf.ByteString
      getCommandBytes();
}
