// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package grpc;

public final class Raft {
  private Raft() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestVoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestVoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestVoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestVoteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AppendEntriesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AppendEntriesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AppendEntriesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AppendEntriesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nraft.proto\"b\n\022RequestVoteRequest\022\014\n\004te" +
      "rm\030\001 \001(\005\022\023\n\013candidateId\030\002 \001(\005\022\024\n\014lastLog" +
      "Index\030\003 \001(\005\022\023\n\013lastLogTerm\030\004 \001(\005\"8\n\023Requ" +
      "estVoteResponse\022\014\n\004term\030\001 \001(\005\022\023\n\013voteGra" +
      "nted\030\002 \001(\010\"\223\001\n\024AppendEntriesRequest\022\014\n\004t" +
      "erm\030\001 \001(\005\022\020\n\010leaderId\030\002 \001(\005\022\024\n\014prevLogIn" +
      "dex\030\003 \001(\005\022\023\n\013prevLogTerm\030\004 \001(\005\022\032\n\007entrie" +
      "s\030\005 \003(\0132\t.LogEntry\022\024\n\014leaderCommit\030\006 \001(\005" +
      "\"6\n\025AppendEntriesResponse\022\014\n\004term\030\001 \001(\005\022" +
      "\017\n\007success\030\002 \001(\010\")\n\010LogEntry\022\014\n\004term\030\001 \001" +
      "(\005\022\017\n\007command\030\002 \001(\t2\213\001\n\013RaftService\022:\n\013R" +
      "equestVote\022\023.RequestVoteRequest\032\024.Reques" +
      "tVoteResponse\"\000\022@\n\rAppendEntries\022\025.Appen" +
      "dEntriesRequest\032\026.AppendEntriesResponse\"" +
      "\000B\010\n\004grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RequestVoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestVoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestVoteRequest_descriptor,
        new java.lang.String[] { "Term", "CandidateId", "LastLogIndex", "LastLogTerm", });
    internal_static_RequestVoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RequestVoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestVoteResponse_descriptor,
        new java.lang.String[] { "Term", "VoteGranted", });
    internal_static_AppendEntriesRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AppendEntriesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AppendEntriesRequest_descriptor,
        new java.lang.String[] { "Term", "LeaderId", "PrevLogIndex", "PrevLogTerm", "Entries", "LeaderCommit", });
    internal_static_AppendEntriesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AppendEntriesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AppendEntriesResponse_descriptor,
        new java.lang.String[] { "Term", "Success", });
    internal_static_LogEntry_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_LogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogEntry_descriptor,
        new java.lang.String[] { "Term", "Command", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
