// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package grpc;

public interface RequestVoteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestVoteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 term = 1;</code>
   */
  int getTerm();

  /**
   * <code>bool voteGranted = 2;</code>
   */
  boolean getVoteGranted();
}
