// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package grpc;

public interface RequestVoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestVoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 term = 1;</code>
   */
  int getTerm();

  /**
   * <code>int32 candidateId = 2;</code>
   */
  int getCandidateId();

  /**
   * <code>int32 lastLogIndex = 3;</code>
   */
  int getLastLogIndex();

  /**
   * <code>int32 lastLogTerm = 4;</code>
   */
  int getLastLogTerm();
}
